chore: refactor

diff --git a/.github/workflows/versions.yml b/.github/workflows/versions.yml
--- a/.github/workflows/versions.yml
+++ b/.github/workflows/versions.yml
@@ -19,6 +19,8 @@ on:
 jobs:
   prereqs:
     runs-on: ubuntu-latest
+    outputs:
+      token: ${{ steps.gh-token-push.outputs.token }}
     steps:
       - name: Github App Token
         # if: ${{ inputs.pr == "true" || inputs.pr == true }}
@@ -32,8 +34,10 @@ jobs:
         id: gh-token-push
         run: |
           if [ "${{ inputs.pr }}" == "true" ]; then
+            echo "using gihub app token..."
             echo token=${{ steps.app-token-push.outputs.token }} >> $GITHUB_OUTPUT
           else
+            echo "using pat..."
             echo token=${{ secrets.GH_TOKEN_PUSH }} >> $GITHUB_OUTPUT
           fi
 
@@ -81,8 +85,6 @@ jobs:
       #
       #     git tag v0.0.1
       #     git push origin v0.0.1
-    outputs:
-      token: ${{ steps.gh-token-push.outputs.token }}
 
   bumpalicious:
     runs-on: ubuntu-latest
@@ -117,37 +119,37 @@ jobs:
       #     pr: "true"
       #     pr_auto_merge: "true"
 
-  cleanup:
-    if: ${{ always() }}
-    runs-on: ubuntu-latest
-    needs:
-      - prereqs
-      - bumpalicious
-    steps:
-      - name: Checkout repo
-        if: ${{ always() }}
-        uses: actions/checkout@v4
-        with:
-          token: ${{ needs.prereqs.outputs.token }}
-          fetch-depth: 0 # Required if you’ll push to an existing branch
-
-      - name: Clean Repo
-        if: ${{ always() }}
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-
-          set -ex
-
-          git pull
-
-          rm -rf workspaces* package.json README.md
-
-          git add -A
-          git diff-index --quiet HEAD || git commit -m "chore: auto-update [skip ci]"
-
-          git push
-
-          git pull
-
-          git push --delete origin v0.0.1
+  # cleanup:
+  #   if: ${{ always() }}
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - prereqs
+  #     - bumpalicious
+  #   steps:
+  #     - name: Checkout repo
+  #       if: ${{ always() }}
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: ${{ needs.prereqs.outputs.token }}
+  #         fetch-depth: 0 # Required if you’ll push to an existing branch
+  #
+  #     - name: Clean Repo
+  #       if: ${{ always() }}
+  #       run: |
+  #         git config user.name "github-actions[bot]"
+  #         git config user.email "github-actions[bot]@users.noreply.github.com"
+  #
+  #         set -ex
+  #
+  #         git pull
+  #
+  #         rm -rf workspaces* package.json README.md
+  #
+  #         git add -A
+  #         git diff-index --quiet HEAD || git commit -m "chore: auto-update [skip ci]"
+  #
+  #         git push
+  #
+  #         git pull
+  #
+  #         git push --delete origin v0.0.1
